version: 2
jobs:
 build:
   parallelism: 1
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
     - run: docker build -f Dockerfile -t niallbyrne/nginx-certified:$CIRCLE_BRANCH .
     - run: docker push niallbyrne/nginx-certified:$CIRCLE_BRANCH
